### ISSUE TITLE
Unable to clone project to local

### ISSUE THREAD

**Issue by clarence-simplex** [pevey/sveltekit-medusa-starter#2]
I tried cloning and encountered 'Please make sure you have the correct access rights and the repository exists' (see attached image)
This looks like an interesting starter kit, do I need to subscribe or logon to test this out?
![clone-error](https://github.com/pevey/sveltekit-medusa-starter/assets/68406978/a8a19688-feaa-41eb-a6db-afdbdc8c6a3b)

**Comment by clarence-simplex** [comment]
Sure, I'll download the zip and unpack. Thanks  pevey!

**Comment by pevey** [comment]
I think you can still do it via the command link using https.  On the main repo page, the green "Code" button is a dropdown that should give different options.
