### ISSUE TITLE
yarn build/run fails with 

### ISSUE THREAD

**Issue by irab** [pevey/sveltekit-medusa-starter#4]
Thanks for the tutorial! 

Following along with the video from SS and 'yarn dev' fails due to the alias config being commented:
https://github.com/pevey/sveltekit-medusa-starter/blob/e56489d11777e0221e4193fb44851e8c7d73cbe4/svelte.config.js#L20-L22

```
Error: [vite]: Rollup failed to resolve import "$src/app.postcss" from "/Users/ira/repos/sveltekit-medusa-starter/src/routes/+layout.svelte".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
``` 

Uncommenting the line fixes the bug

**Comment by irab** [comment]
Not sure if it's changed for a reason, so no PR

**Comment by pevey** [comment]
Hmm. I think this slipped in when I was changing some config to remove the melt-ui preprocessor.  Feel free to do a PR, I will merge it in.  If you'd rather not, no worries.  I'll fix it in a couple of days to give you time.

**Comment by pevey** [comment]
This should be fixed with the latest commit.
