### ISSUE TITLE
Demo site is broken

### ISSUE THREAD

**Issue by brussli1** [pevey/sveltekit-medusa-starter#9]
It only shows home to your site

**Comment by pevey** [comment]
There is no demo site.  Not sure what you're referring to.

**Comment by 0x0m0t0** [comment]
He's referring to this link in the about section of the project.
https://pevey.com/sveltekit-medusa-storefront


<img width="1309" alt="Screenshot 2024-02-23 at 22 14 38" src="https://github.com/pevey/sveltekit-medusa-starter/assets/132828816/0a85eace-cbed-4b6e-baac-c71bab03fc55">
